Algorithms/Algorithms/Controllers/LocalBeamSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Algorithms.Models;
using Algorithms.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Algorithms.Controllers
{
    public class LocalBeamSearchController : Controller
    {
        private FunctionsInterface _IFunctions;
        public LocalBeamSearchController(FunctionsInterface IFunctions)
        {
            _IFunctions = IFunctions;
        }
        
        public IActionResult Index()
        {
            int[] a = new int[16] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            LocalBeamSearchVM VM = new LocalBeamSearchVM()
            {
                array = a,
                dimension = 4,
                dimensions = new List<SelectListItem>()
                {
                    new SelectListItem{Text="4x4",Value="4"},
                    new SelectListItem{Text="5x5",Value="5"},
                    new SelectListItem{Text="6x6",Value="6"},
                    new SelectListItem{Text="7x7",Value="7"},
                    new SelectListItem{Text="8x8",Value="8"},
                    new SelectListItem{Text="9x9",Value="9"},
                    new SelectListItem{Text="10x10",Value="10"},
                    new SelectListItem{Text="11x11",Value="11"},
                    new SelectListItem{Text="12x12",Value="12"},
                }
                
            };
            return View(VM);
        }
        public IActionResult GenerateRandomState(int dim,int states,int maxCounter)
        {
            int[][] array = _IFunctions.GenerateArray(dim);
            
            LocalBeamSearchVM VM = new LocalBeamSearchVM()
            {
                array = _IFunctions.array2Dto1D(array, dim),
                dimension = dim,
                heuristic = _IFunctions.Heuristic(array, dim),
                nmbrStates=states,
                maxCounter=maxCounter,
                dimensions = new List<SelectListItem>()
                {
                    new SelectListItem{Text="4x4",Value="4"},
                    new SelectListItem{Text="5x5",Value="5"},
                    new SelectListItem{Text="6x6",Value="6"},
                    new SelectListItem{Text="7x7",Value="7"},
                    new SelectListItem{Text="8x8",Value="8"},
                    new SelectListItem{Text="9x9",Value="9"},
                    new SelectListItem{Text="10x10",Value="10"},
                    new SelectListItem{Text="11x11",Value="11"},
                    new SelectListItem{Text="12x12",Value="12"},
                },

            };

            return View("Index", VM);
        }
        
        public IActionResult LocalBeamSearchA(string stringArray, int dim,int states,int maxCounter)
        {
            int[] array = _IFunctions.StringToInt(stringArray, dim);
            int[][] Array = _IFunctions.array1Dto2D(array, dim);

            State[] BestStates = new State[states];
            for (int i = 0; i < states; i++)    //generating k random states
            {
                BestStates[i] = new State(dim);
                BestStates[i].niz= _IFunctions.GenerateArray(dim);
                BestStates[i].h = _IFunctions.Heuristic(BestStates[i].niz,dim);
            }
            bool change = true;
            while (change)  //sort initial states
            {
                change = false;
                for (int i = 0; i < states - 1; i++)
                {
                    if (BestStates[i].h > BestStates[i + 1].h)
                    {
                        State s = BestStates[i];
                        BestStates[i] = BestStates[i + 1];
                        BestStates[i + 1] = s;
                        change = true;
                    }
                }
            }
            State[] allStates = new State[states * states];
            int counter2 = 0;
            while (BestStates[0].h != 0 && counter2 < maxCounter) // do until we find the state with h0, or until the counter reaches final status
            {
                int counter = 0;

                for (int i = 0; i < states; i++)
                {
                    for (int j = 0; j < states; j++)
                    {
                        allStates[counter] = new State(dim);
                        allStates[counter].niz =_IFunctions.rndSuccessor(_IFunctions.CopyRow(BestStates[j].niz,dim),dim); //for k states we are making k random single moves
                        allStates[counter].h = _IFunctions.Heuristic(allStates[counter].niz,dim);
                        counter++;
                    }
                }

                change = true;  //sort expanded array
                while (change)
                {
                    change = false;
                    for (int i = 0; i < states * states - 1; i++)
                    {
                        if (allStates[i].h > allStates[i + 1].h)
                        {
                            State s = allStates[i];
                            allStates[i] = allStates[i + 1];
                            allStates[i + 1] = s;
                            change = true;
                        }
                    }
                }
                for (int i = 0; i < states; i++)    //selecting k best states
                {
                    BestStates[i].niz = _IFunctions.CopyRow(allStates[i].niz,dim);
                    BestStates[i].h = _IFunctions.Heuristic(allStates[i].niz,dim);
                }
                counter2++;
            }
            LocalBeamSearchVM VM = new LocalBeamSearchVM()
            {
                array = _IFunctions.array2Dto1D(BestStates[0].niz, dim),
                dimension = dim,
                heuristic = _IFunctions.Heuristic(BestStates[0].niz, dim),
                dimensions = new List<SelectListItem>()
                {
                    new SelectListItem{Text="4x4",Value="4"},
                    new SelectListItem{Text="5x5",Value="5"},
                    new SelectListItem{Text="6x6",Value="6"},
                    new SelectListItem{Text="7x7",Value="7"},
                    new SelectListItem{Text="8x8",Value="8"},
                    new SelectListItem{Text="9x9",Value="9"},
                    new SelectListItem{Text="10x10",Value="10"},
                    new SelectListItem{Text="11x11",Value="11"},
                    new SelectListItem{Text="12x12",Value="12"},
                },
                counter = counter2,
                nmbrStates=states,
                maxCounter=maxCounter
                
            };
            return PartialView("LocalBeamSearchDone", VM);
        }
    }
}

Algorithms/Algorithms/Views/LocalBeamSearch/Index.cshtml
@model Algorithms.ViewModel.LocalBeamSearchVM;
@{
    //Layout = 0;
    ViewData["Title"] = "Index";
    var k = 0;
}

<style>
    .chessboard {
        @*width:@(Model.dimension * 80 + 50 + "px");
        height:@(Model.dimension * 80 + 50 + "px");*@
        width:604.4px;
        height:604.4px;
    margin: 20px;
    border: 25px solid #333;
    display:inline-block;
}
.black {
    float: left;
    width: @(554.4/Model.dimension+"px");
    height: @(554.4/Model.dimension+"px");
    background-color: #999;
      font-size:50px;
    text-align:center;
    display: table-cell;
    vertical-align:middle;
}
.white {
    float: left;
    width: @(554.4/Model.dimension+"px");
    height: @(554.4/Model.dimension+"px");
    background-color: #fff;
    font-size:50px;
    text-align:center;
    display: table-cell;
    vertical-align:middle;
</style>
<h3>LocalBeamSearch</h3>

<div id="LocalBeamSearchDiv">
    <div class="chessboard">
        @for (int i = 0; i < Model.dimension; i++)
        {
            if (i % 2 == 0)
            {
                for (int j = 0; j < Model.dimension; j++)
                {
                    if (j % 2 == 0)
                    {
                        if (Model.array[k] == 1)
                        {
                            <div class="white">&#9819;</div>

                        }
                        else
                        {
                            <div class="white"></div>
                        }
                    }
                    else
                    {
                        if (Model.array[k] == 1)
                        {
                            <div class="black">&#9819;</div>

                        }
                        else
                        {
                            <div class="black"></div>

                        }
                    }
                    k++;
                }

            }
            else
            {
                for (int j = 0; j < Model.dimension; j++)
                {
                    if (j % 2 == 0)
                    {
                        if (Model.array[k] == 1)
                        {
                            <div class="black">&#9819;</div>

                        }
                        else
                        {
                            <div class="black"></div>
                        }
                    }
                    else
                    {
                        if (Model.array[k] == 1)
                        {
                            <div class="white">&#9819;</div>

                        }
                        else
                        {
                            <div class="white"></div>

                        }
                    }
                    k++;
                }
            }
        }


    </div>
    <div style="display:inline-block;float:right" id="Options">
        <form asp-action="GenerateRandomState">
            <select name="dim" asp-for="dimension" asp-items=@Model.dimensions>
            </select>
            <input name="states"asp-for="nmbrStates" hidden />
            <input asp-for="heuristic" hidden value=@Model.heuristic />
            <p><span>Heuristic: @Model.heuristic</span></p>
            <p><span>Counter: @Model.counter</span></p>
            <input type="submit" value="Generate random state" />
        </form>   
        <br />
        <table>
            <tr><td>Number of states</td><td><input id="nbrStates" asp-for="nmbrStates" /></td></tr>
            <tr><td>Max number of itterations</td><td><input id="maxCounterID" asp-for="maxCounter" /></td></tr>
        </table>
         <br />

        <a onclick="LocalBeamSearch()" class="btn btn-info">Execute algorithm</a>
    </div>
</div>
<script>
    function LocalBeamSearch() {
        var dim=@Model.dimension;
        var Array = "@(Model.array == null ? string.Empty : string.Join("", Model.array))";
        $.ajax({
            url: '@Url.Action("LocalBeamSearchA", "LocalBeamSearch")',
            method: 'POST',
            data: {
                //test: test3,
                stringArray: Array,
                dim:@Model.dimension,
                states: $("#nbrStates").val(),
                maxCounter: $("#maxCounterID").val(),
            },
            success: function (data) {
                $("#LocalBeamSearchDiv").html(data);
            }
        });
    }

</script>

Algorithms/Algorithms/Views/LocalBeamSearch/LocalBeamSearchDone.cshtml
@model Algorithms.ViewModel.LocalBeamSearchVM;
@{
    //Layout = 0;
    ViewData["Title"] = "LocalBeamSearchDone";
    var k = 0;
}


<div class="chessboard">
    @for (int i = 0; i < Model.dimension; i++)
    {
        if (i % 2 == 0)
        {
            for (int j = 0; j < Model.dimension; j++)
            {
                if (j % 2 == 0)
                {
                    if (Model.array[k] == 1)
                    {
                        <div class="white">&#9819;</div>

                    }
                    else
                    {
                        <div class="white"></div>
                    }
                }
                else
                {
                    if (Model.array[k] == 1)
                    {
                        <div class="black">&#9819;</div>

                    }
                    else
                    {
                        <div class="black"></div>

                    }
                }
                k++;
            }

        }
        else
        {
            for (int j = 0; j < Model.dimension; j++)
            {
                if (j % 2 == 0)
                {
                    if (Model.array[k] == 1)
                    {
                        <div class="black">&#9819;</div>

                    }
                    else
                    {
                        <div class="black"></div>
                    }
                }
                else
                {
                    if (Model.array[k] == 1)
                    {
                        <div class="white">&#9819;</div>

                    }
                    else
                    {
                        <div class="white"></div>

                    }
                }
                k++;
            }
        }
    }


</div>
<div style="display:inline-block;float:right" id="Options">
    <form asp-action="GenerateRandomState">
        <select name="dim" asp-for="dimension" asp-items=@Model.dimensions>
        </select>
        <input asp-for="dimension" hidden />
        <input asp-for="maxCounter" hidden />
        <input asp-for="heuristic" hidden value=@Model.heuristic />
        <input name="states" asp-for="nmbrStates" hidden />
        <p><span>Heuristic: @Model.heuristic</span></p>
        <p><span>Counter: @Model.counter</span></p>
        <input type="submit" value="Generate random state" />
    </form>
    <br />
    <table>
        <tr><td>Number of states</td><td><input id="nbrStates" asp-for="nmbrStates" /></td></tr>
        <tr><td>Max number of itterations</td><td><input id="maxCounterID" asp-for="maxCounter" /></td></tr>
    </table>
    <br />
    <a style="pointer-events: none; cursor: default; background-color:grey" ; class="btn btn-info">Execute algorithm</a>
</div>