TicTac/TicTac/Controllers/AlphaBetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TicTac.Models;
using TicTac.ViewModel;

namespace TicTac.Controllers
{
    public class AlphaBetaController : Controller
    {
        public IActionResult Index(int Depth, Player player=(Player)0, int PlayerScore=0, int EqualScore=0, int CompScore=0)
        {
             
            //char[] array;
            //if (HumanOnMove)
            //{
                char []array  = new char[9] {'0', '0', '0', '0', '0', '0', '0', '0', '0' };
            Node s=new Node();
            if(player==(Player)1)
            {
                char[][] Array = new char[3][];
                Array[0] = new char[3] { '0', '0', '0' };
                Array[1] = new char[3] { '0', '0', '0' };
                Array[2] = new char[3] { '0', '0', '0' };
                s.niz = CopyRow(Array);
                s.h = Heuristic(s.niz);
                List<object> result = alphabet(s, Depth, int.MinValue, int.MaxValue, (Player)1);
                s = (Node)result[1];
                s.h = Heuristic(s.niz);
                int brojac = 0;
                for (int i = 0; i < 3; i++)
                {
                    for (int j = 0; j < 3; j++)
                    {
                        array[brojac++]=s.niz[i][j];
                    }
                }
            }
            
            AlphaBetaVM VM = new AlphaBetaVM()
            {
                array = array,
                depth=Depth,
                player=player,
                isLeaf="false",
                playerScore=PlayerScore,
                compScore=CompScore,
                equalScore=EqualScore,
                depths = new List<SelectListItem>()
                {
                    new SelectListItem{Text="Too Easy (1)",Value="1"},
                    new SelectListItem{Text="Easy (2)",Value="2"},
                    new SelectListItem{Text="Simple (3)",Value="3"},
                    new SelectListItem{Text="Medium (4)",Value="4"},
                    new SelectListItem{Text="Harder (5)",Value="5"},
                    new SelectListItem{Text="Hard (6)",Value="6"},
                    new SelectListItem{Text="Very difficult (7)",Value="7"},
                    new SelectListItem{Text="Extreme (8)",Value="8"},
                    new SelectListItem{Text="Impossible (9)",Value="8"}
                }
            };
            return View(VM);
        }
        public IActionResult NextPlayer(int Depth)
        {

            return View();
        }
        public char[][] StringToChar2D(string stringArray)
        {
            char[][] array = new char[3][];
            int brojac = 0;
            for (int i = 0; i <3; i++)
            {
                array[i] = new char[3];
                for (int j = 0; j < 3; j++)
                {
                    array[i][j] = stringArray[brojac++];
                }
            }
            return array;
        }
        public static bool IsLeaf(Node s)
        {
            if (s.h == 1000 || s.h == -1000)
                return true;
            for (int i = 0; i < 3; i++)
            {
                for (int j = 0; j < 3; j++)
                {
                    if (s.niz[i][j] == '0')
                        return false;
                }
            }
            return true;
        }
        static char[][] CopyRow(char[][] niz)
        {
            char[][] niz2 = new char[3][];
            for (int i = 0; i < 3; i++)
            {
                niz2[i] = new char[3];
                for (int j = 0; j < 3; j++)
                {
                    niz2[i][j] = niz[i][j];
                }
            }
            return niz2;
        }
        public static int Heuristic(char[][] niz)
        {
            int h;
            int sumX = 0;
            int sumO = 0;
            int brojacX = 0;
            int brojacO = 0;
            int brojacXO = 0;
            for (int i = 0; i < 3; i++)
            {
                for (int j = 0; j < 3; j++)
                {
                    if (niz[i][j] == 'X')
                    {
                        brojacX++;
                    }
                    else if (niz[i][j] == 'O')
                    {
                        brojacO++;
                    }
                    else
                    {
                        brojacXO++;
                    }
                }
                if (brojacX == 3)
                {
                    return 1000;
                }
                else if (brojacO == 3)
                    return -1000;
                else if (brojacXO == 3)
                {
                    sumO++;
                    sumX++;
                }
                else if (brojacX + brojacXO == 3)
                    sumX++;
                else if (brojacO + brojacXO == 3)
                    sumO++;
                brojacO = 0;
                brojacX = 0;
                brojacXO = 0;
            }
            for (int j = 0; j < 3; j++)
            {
                for (int i = 0; i < 3; i++)
                {
                    if (niz[i][j] == 'X')
                    {
                        brojacX++;
                    }
                    else if (niz[i][j] == 'O')
                    {
                        brojacO++;
                    }
                    else
                    {
                        brojacXO++;
                    }
                }
                if (brojacX == 3)
                {
                    return 1000;
                }
                else if (brojacO == 3)
                    return -1000;
                else if (brojacXO == 3)
                {
                    sumO++;
                    sumX++;
                }
                else if (brojacX + brojacXO == 3)
                    sumX++;
                else if (brojacO + brojacXO == 3)
                    sumO++;
                brojacO = 0;
                brojacX = 0;
                brojacXO = 0;
            }
            for (int i = 0; i < 3; i++)
            {
                if (niz[i][i] == 'X')
                {
                    brojacX++;
                }
                else if (niz[i][i] == 'O')
                {
                    brojacO++;
                }
                else
                {
                    brojacXO++;
                }
            }
            if (brojacX == 3)
            {
                return 1000;
            }
            else if (brojacO == 3)
                return -1000;
            else if (brojacXO == 3)
            {
                sumO++;
                sumX++;
            }
            else if (brojacX + brojacXO == 3)
                sumX++;
            else if (brojacO + brojacXO == 3)
                sumO++;
            brojacO = 0;
            brojacX = 0;
            brojacXO = 0;
            int n = 2;
            for (int i = 0; i < 3; i++)
            {
                if (niz[i][n] == 'X')
                {
                    brojacX++;
                }
                else if (niz[i][n] == 'O')
                {
                    brojacO++;
                }
                else
                {
                    brojacXO++;
                }
                n--;
            }
            if (brojacX == 3)
            {
                return 1000;
            }
            else if (brojacO == 3)
                return -1000;
            else if (brojacXO == 3)
            {
                sumO++;
                sumX++;
            }
            else if (brojacX + brojacXO == 3)
                sumX++;
            else if (brojacO + brojacXO == 3)
                sumO++;
            h = sumX - sumO;
            return h;
        }
        public static List<Node> PossibleMoves(Node s, Player p)
        {
            List<Node> possibleMoves = new List<Node>();
            int brojac = 0;
            for (int i = 0; i < 3; i++)
            {
                for (int j = 0; j < 3; j++)
                {
                    if (s.niz[i][j] == '0')
                    {
                        possibleMoves.Add(new Node());
                        possibleMoves[brojac].niz = CopyRow(s.niz);
                        if (p == (Player)0)
                        {
                            possibleMoves[brojac].niz[i][j] = 'O';
                        }
                        else
                        {
                            possibleMoves[brojac].niz[i][j] = 'X';
                        }
                        possibleMoves[brojac].h = Heuristic(possibleMoves[brojac].niz);
                        brojac++;
                    }
                }
            }
            return possibleMoves;
        }
        public static List<object> alphabet(Node node, int depth, int α, int ß
            , Player player)
        {
            if (depth == 0 || IsLeaf(node)) //
                return new List<object>() { node.h, node }; //if we found the Leaf or we came to the marked depth we are returning that node
            if (player == (Player)1)//If the maximizing player is on move we are calculating next move with the highest heuristi(state with highest possibility of winning the game)
            {
                int value = int.MinValue;
                List<Node> children = PossibleMoves(node, player);  //Calculating all possible moves for next player
                Node move = null;
                foreach (var child in children)
                {
                    List<object> result = alphabet(child, depth - 1, α, ß, (Player)0);//for every child we are looking for the one with highest heuristic
                    if ((int)result[0] > value)
                    {
                        value = (int)result[0];
                        move = child;
                    }
                    if (value > α)

TicTac/TicTac/Views/AlphaBeta/AlphaBetaA.cshtml
@model TicTac.ViewModel.AlphaBetaVM;

@{
    ViewData["Title"] = "AlphaBetaA";
    int brojac = 0;
}
<input asp-for="isLeaf" hidden />
<input id="playerID" value=@Model.player hidden />
<input asp-for="heuristic" hidden />
<input asp-for="player" hidden />
<input asp-for="playerScore" hidden />
<input asp-for="compScore" hidden />
<input asp-for="equalScore" hidden />
@for (int i = 0; i < 3; i++)
{
    for (int j = 0; j < 3; j++)
    {
        <div class="square" onclick="alphaBetaReset()">
            @if (Model.array[brojac] != '0')
            {
                <input id=@("index"+brojac) value=@Model.array[brojac] hidden />
                <p style="font-size:60px; text-align:center">@Model.array[brojac]</p>
            }
            else
            {
                <div style="width:100%;height:100%;" onclick="alphaBeta(@brojac)">

                    <input id=@("index"+brojac) value=@Model.array[brojac] hidden />
                </div>
            }
        </div>
        brojac++;
    }
}
<table>
    <tr>
        <td style="padding:10px; text-align:center;">Player</td>
        <td style="padding:10px; text-align:center;">Draw</td>
        <td style="padding:10px;text-align:center;">Computer</td>
    </tr>
    <tr>
        <td style="padding:10px;text-align:center;"><input id="playerScoreID" value=@Model.playerScore readonly/></td>
        <td style="padding:10px;text-align:center;"><input id="equalScoreID" value=@Model.equalScore readonly/></td>
        <td style="padding:10px;text-align:center;"><input id="compScoreID" value=@Model.compScore readonly/></td>
    </tr>
</table>

TicTac/TicTac/Views/AlphaBeta/Index.cshtml
@model TicTac.ViewModel.AlphaBetaVM;
@{
    ViewData["Title"] = "Index";
    int brojac = 0;
}

<style>
    .mid-square {
        height: 100px;
        width: 100px;
        border-right: 1px solid black;
        border-left: 1px solid black;
        border-bottom: 1px solid black;
        float: left;
        box-sizing: border-box;
    }
    .left-square {
        height: 100px;
        width: 100px;
        border-bottom: 1px solid black;
        float: left;
        box-sizing: border-box;
    }
    .right-square {
        height: 100px;
        width: 100px;
        border-bottom: 1px solid black;
        float: left;
        box-sizing: border-box;
    }
    .square {
        height: 100px;
        width: 100px;
        border: 1px solid black;
        float: left;
        box-sizing: border-box;
    }

    .row {
        width: 300px;
    }
    td{
        font-size:25px;
    }
</style>
<h1>Index</h1>

<div>
    <select asp-for="depth" asp-items=@Model.depths>
        <option>Difficulty</option>
    </select>
</div>
<div id="TargetDiv" class="row">
    <input asp-for="isLeaf" hidden/>
    <input asp-for="player" hidden />
    <input asp-for="heuristic" hidden />
    <input asp-for="playerScore" hidden />
    <input asp-for="compScore" hidden />
    <input asp-for="equalScore" hidden />
    @for (int i = 0; i < 3; i++)
    {
        for (int j = 0; j < 3; j++)
        {
            <div class="square">
                @if (Model.array[brojac] != '0')
                {
                    <input id=@("index"+brojac) value=@Model.array[brojac] hidden />
                    <p style="font-size:60px; text-align:center">@Model.array[brojac]</p>
                }
                else
                {
                    <div style="width:100%;height:100%;" onclick="alphaBeta(@brojac)">

                        <input id=@("index"+brojac) value=@Model.array[brojac] hidden />
                    </div>
                }
            </div>
            brojac++;
        }
    }
    <br />
    <table>
        <tr>
            <td style="padding:10px;text-align:center;">Player</td>
            <td style="padding:10px;text-align:center;">Draw</td>
            <td style="padding:10px;text-align:center;">Computer</td>
        </tr>
        <tr>
            <td style="padding:10px;text-align:center;"><input id="playerScoreID" value=@Model.playerScore readonly/></td>
            <td style="padding:10px;text-align:center;"><input id="equalScoreID" value=@Model.equalScore readonly/></td>
            <td style="padding:10px;text-align:center;"><input id="compScoreID" value=@Model.compScore readonly /></td>
        </tr>
    </table>
    @*<div class="row" >
            <div class="left-square">

            </div>
            <div class="mid-square"></div>1
            <div class="right-square"></div>
        </div>
        <div class="row">
            <div class="left-square"></div>
            <div class="mid-square"></div>
            <div class="right-square"></div>
        </div>
        <div class="row">
            <div class="left-square" style="border-bottom:none"></div>
            <div class="mid-square" style="border-bottom:none"></div>
            <div class="right-square" style="border-bottom:none"></div>
        </div>*@

</div>
<script>
    function alphaBeta(index) {
        
        if (document.getElementById("isLeaf").value == "true") {
            return;
        }
        //var Array = "@(Model.array == null ? string.Empty : string.Join("", Model.array))";
        var Array=[];
        for (var i = 0; i < 9; i++) {
            Array[i] = document.getElementById("index"+i).value;               
        }
        if(document.getElementById("player").value=="MIN")
            Array[index] = 'X';
        else
            Array[index] = 'O';
        var a = Array.join("");
        $.ajax({
            url: '@Url.Action("AlphaBetaA", "AlphaBeta")',
            method: 'POST',
            data: {
                stringArray: a,
                depth:$("#depth").val(),
                player: $("#player").val(),
                PlayerScore:$("#playerScoreID").val(),
                EqualScore:$("#equalScoreID").val(),
                CompScore:$("#compScoreID").val()
            },
            success: function (data) {
                $("#TargetDiv").html(data);
                
            }
        });
    }
    
    function alphaBetaReset() {
        
        if (document.getElementById("isLeaf").value == "true") {
            window.location.href = "/AlphaBeta/Index?Depth=" + document.getElementById("depth").value +
                "&player=" + document.getElementById("playerID").value + "&PlayerScore=" + document.getElementById("playerScoreID").value +
                "&EqualScore="+document.getElementById("equalScoreID").value+"&CompScore="+document.getElementById("compScoreID").value;
            
        }
    }
</script>